version: '2'
services:
  web:
    build: .
    ports:
      - "3300:3300"
    volumes:
      - .:/code
    links:
      - redis
      - mongodb
  redis:
    image: "redis"

  mongodb:
    image: "mongo"